### ISSUE TITLE
Set up Continuous Integration, E.g. Travis CI.

### ISSUE THREAD

**Issue by v-bosch** [v-bosch/TruCol#2]
CI could be used to test:
- [ ] The frontend
- [x] The solidity contracts that showcase the protocol
- [ ] New contracts that are added by the user

Means to test the solidity contracts [could be](https://ethereum.stackexchange.com/questions/607/how-to-unit-test-smart-contracts):
- [Populus](https://populus.readthedocs.io/en/latest/) Written in python tests via pytest
 - [Truffle](https://www.trufflesuite.com/docs/truffle/testing/testing-your-contracts) Written in JavaScript, test via Mocha
 - [Embark](https://iurimatias.github.io/embark-framework/) Written in JavaScript, test via Mocha
 - [Dapple](https://github.com/NexusDevelopment/dapple) Written in Javascript, tests solidity
 - [oyente](https://github.com/enzymefinance/oyente) python

**Comment by a-t-0** [comment]
https://blog.coinfabrik.com/test-solidity-smart-contracts-using-travis-ci/

**Comment by a-t-0** [comment]
Chose to select Truffle, Travis CI is implemented with Truffle. NodeJS frontend is not yet included in CI tests, and that is not considered a priority right now.
